#!/usr/bin/env python3

import time
import random
from datetime import datetime
import json
import os

DEBUG = True
REPEATS = 10 if not DEBUG else 1
MAX_WAIT = 10 if not DEBUG else 0
MSG = "GOGOGO (hit enter)"
project_dir = os.path.dirname(os.path.realpath(__file__))


print("Your task is to hit enter as quickly as possible once you see the text '{MSG}' is printed. This test will be repeated {REPEATS} times.")
name = input("Enter your name: ")
input("Hit enter to start.")

times = []
for i in range(REPEATS):
    time.sleep((1 if not DEBUG else 0) + random.random() * MAX_WAIT)
    start_time = time.time()
    input(MSG)
    times.append(time.time() - start_time)

data_safe = datetime.now().isoformat()
with open(f'{project_dir}/data/{data_safe}_{name}.json', 'w') as f:
    json.dump(times, f)
